---
- hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: BSRGBCENTTEST
        location: westus
      register: rg
    - debug:
        var: rg

