---
- hosts: azcsuffrgansi-test
  become: true
  tasks:
    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started


          # ansible-playbook -b -i ~/bin/azure_rm.py  playbooks/nginx.yml -k --become-user=root -K
          # ansible -b -kK -i ~/bin/azure_rm.py bseusrgansi-test -m shell -a "ifconfig"